[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pybeso"
version = "0.1.1"
description = "Python communication with BESO"
authors = [{ name="Mikolaj"}]
dependencies = []

[project.scripts]
beso = "beso.main:main"