[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "pybeso"
version = "0.1.0"
description = "Python communication with BESO"
authors = [{ name="Mikolaj"}]
dependencies = ["aiohttp"]

[project.scripts]
beso = "beso.main:main"